version: '3.3'
services:

  db:
    image: postgres:13.3-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  backend:
    image: kors557/foodgramback:v1 
    restart: always 
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../backend/.env

  frontend:
    image: kors557/foodgramfrot:v1
    volumes:
      - ../frontend/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
